This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./compile.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file compile.acn....done (108 entries accepted, 0 rejected).
Sorting entries....done (809 comparisons).
Generating output file compile.acr....done (72 lines written, 0 warnings).
Output written in compile.acr.
Transcript written in compile.alg.
