This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./compile.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file compile.acn....done (717 entries accepted, 0 rejected).
Sorting entries.........done (8659 comparisons).
Generating output file compile.acr....done (255 lines written, 0 warnings).
Output written in compile.acr.
Transcript written in compile.alg.
