#!/bin/sh

#fix characters in the bibtex db
sed 's/º/\\textdegree\{\}/g' thesis.bib >> TMPBIB;
mv TMPBIB thesis.bib;

#spellcheck
for i in $(find ../ | grep .tex); do
  aspell --personal=./dictionary check $i;
done

#tell pdflatex not to be paranoid about /includes
export openout_any=a;

pdflatex compile;
makeglossaries compile;
bibtex compile;
pdflatex compile;
pdflatex compile;
open compile.pdf;
